apiVersion: apps/v1
kind: Deployment

metadata:
  name: springboot-app
  namespace: prod

spec:

  replicas: 2

  selector:
    matchLabels:
      app: springboot-app

  template:

    metadata:
      labels:
        app: springboot-app

    spec:

      containers:

        - name: springboot-app

          image: rakshithaj657/springboot-app:IMAGE_TAG_PLACEHOLDER

          imagePullPolicy: Always

          ports:

            - name: http
              containerPort: 8080

          env:

            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/foodfiesta?createDatabaseIfNotExist=true"

            - name: SPRING_DATASOURCE_USERNAME
              value: "root"

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD

          readinessProbe:

            tcpSocket:
              port: 8080

            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:

            tcpSocket:
              port: 8080

            initialDelaySeconds: 60
            periodSeconds: 20