apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: mysql
  namespace: prod

spec:

  serviceName: mysql-service

  replicas: 1

  selector:
    matchLabels:
      app: mysql

  template:

    metadata:
      labels:
        app: mysql

    spec:

      containers:

        - name: mysql

          image: mysql:8.0

          imagePullPolicy: IfNotPresent

          ports:

            - name: mysql
              containerPort: 3306

          env:

            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE

          volumeMounts:

            - name: mysql-storage
              mountPath: /var/lib/mysql

          readinessProbe:

            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h 127.0.0.1 -uroot -p"$MYSQL_ROOT_PASSWORD"

            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:

            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h 127.0.0.1 -uroot -p"$MYSQL_ROOT_PASSWORD"

            initialDelaySeconds: 40
            periodSeconds: 20

      volumes:

        - name: mysql-storage

          persistentVolumeClaim:
            claimName: mysql-pvc